### ISSUE TITLE
ontologize Monkeypox fields

### ISSUE THREAD

**Issue by cmrn-rhi** [GenEpiO/genepio#42]
**Fields:**
- sequenced by
- sequenced by contact email
- sequenced by contact address

**Picklists:** TBD or N/A

**To-Dos:**
- [x] mint new IDs
- [x] update DataHarmonizer template(s)
- [x] update ROBOT table(s)
- [x] update GENEPIO

**Comment by cmrn-rhi** [comment]
Note for next release - minor definition changes to:

- sequence submitted by [GENEPIO:0001159]
- sequence submitter contact email [GENEPIO:0001165]
- sequence submitter contact address [GENEPIO:0001167]

Rationale: It was found that the definitions for the `sequence submitted by` terms were actually more appropriate for `sequenced by` terms and that there is a need for both. A comment was added to all terms to help direct users to the other terms in case those were more applicable to their work/need.
